#!/usr/bin/env bash

TASKBIN="task rc.defaultwidth=100000"

TEMPTASK="/tmp/$(basename $0).task.$RANDOM.taskoutline"
TEMPWORK="/tmp/$(basename $0).work.$RANDOM.taskoutline"
TEMPCMDS="/tmp/$(basename $0).cmds.$RANDOM.taskoutline"

$TASKBIN tree $@ | grep -v "defaultwidth=100000" > $TEMPTASK
tasktree.py < $TEMPTASK > $TEMPWORK

$EDITOR $TEMPWORK
taskflat.py $TEMPTASK $@ < $TEMPWORK > $TEMPCMDS

if [ -s "$TEMPCMDS" ]; then
  echo "Running"
  cat $TEMPCMDS

  #read -p "Are you sure? " -n 1
  #if [[ $REPLY =~ ^[Yy]$ ]]
  #then
    #echo ""
    chmod +x $TEMPCMDS
    $TEMPCMDS
  #fi
  #rm $TEMPCMDS
fi

rm $TEMPTASK
rm $TEMPWORK
rm $TEMPCMDS
